export const fitnessClasses = [
  {
    id: 1,
    title: "HIIT Training",
    description: "High-intensity interval training to boost your metabolism.",
    image: "https://www.guardian.in/cdn/shop/articles/best-hiit-workouts.jpg?v=1705472719",
    duration: "45 min",
    capacity: "12 people",
    instructor: "Sarah Johnson",
  },
  {
    id: 2,
    title: "Yoga Flow",
    description: "Gentle flowing movements to improve flexibility and reduce stress.",
    image: "https://relajemos.com/wp-content/uploads/2019/02/yoga-flow-principal.jpg",
    duration: "60 min",
    capacity: "15 people",
    instructor: "Maria Garcia",
  },
  {
    id: 3,
    title: "Strength Training",
    description: "Build muscle and increase strength with our comprehensive weight training program.",
    image: "https://res.cloudinary.com/hydrow/image/upload/f_auto/w_3840/q_80/v1741799501/Blog/the-15-best-strength-training-exercises.jpg",
    duration: "50 min",
    capacity: "8 people",
    instructor: "Mike Thompson",
  },
  {
    id: 4,
    title: "Pilates Core",
    description: "Strengthen your core and improve posture with targeted Pilates exercises.",
    image: "https://activefitnessmedowie.com.au/wp-content/uploads/2025/02/Woman-doing-the-side-plank-exercise-on-mat-in-gym.jpg",
    duration: "45 min",
    capacity: "10 people",
    instructor: "Emma Wilson",
  },
  {
    id: 5,
    title: "Cardio Dance",
    description: "Fun and energetic dance workout that combines cardio with rhythm.",
    image: "https://www.gimnasiosigueiro.com/sites/default/files/field/image/11244711_10206943814098942_1801164422117604620_n.jpg",
    duration: "55 min",
    capacity: "20 people",
    instructor: "Lisa Rodriguez",
  },
  {
    id: 6,
    title: "CrossFit",
    description: "Intense functional fitness training for maximum results and endurance.",
    image: "https://www.hola.com/horizon/landscape/7793f9ed3467-pareja-cuerdas-t.jpg",
    duration: "60 min",
    capacity: "12 people",
    instructor: "David Chen",
  },
  {
    id: 7,
    title: "Spin Class",
    description: "High-energy indoor cycling class with motivating music and coaching.",
    image: "https://fuelfitnessclubs.com/wp-content/uploads/2020/03/5-Great-Reasons-to-Try-a-Spin-Class.jpg",
    duration: "45 min",
    capacity: "16 people",
    instructor: "Alex Turner",
  },
  {
    id: 8,
    title: "Aqua Aerobics",
    description: "Low-impact water-based exercise perfect for all fitness levels.",
    image: "https://www.ifafitness.com/images/aqua-training.jpg",
    duration: "40 min",
    capacity: "18 people",
    instructor: "Rachel Green",
  },
  {
    id: 9,
    title: "Meditation & Mindfulness",
    description: "Relax and center yourself with guided meditation and breathing exercises.",
    image: "https://t3.ftcdn.net/jpg/06/03/27/00/360_F_603270051_cuxIcMvh6zuOK44PT4pR54lz5rQP8nE8.jpg",
    duration: "30 min",
    capacity: "25 people",
    instructor: "Zen Master Kim",
  },
];

